version: '3'
services:
  node:
    image: "node:20.10.0"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./JmrServiceNoSSR:/home/node/app
    expose:
      - "4200"
    ports:
      - "4200:4200"
    command: "npm run start"